name: 6 In 602
favicon: null
layout_spectrum: 0.04465070436708629
typography_spectrum: 0.017150420462712646
title: '6 In 602: Sunsets & Sunrises In AZ'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73349047-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13164385594427586
  lightness: 0.4181561307050288
  saturation: 0.9255565851926804
  rhythmicContrast: 0.7350033051334321
purpose: []
